version: build.{build}
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
  - Any CPU
matrix:
  exclude:
    - configuration: Debug
      platform: x86
    - configuration: Debug
      platform: x64
    - configuration: Release
      platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-NBi-SqlServer.ps1 $nuget_version
test_script:
- cmd: nunit3-console NBi.Testing.Core.SqlServer.Unit\bin\debug\NBi.Testing.Core.SqlServer.Unit.dll
artifacts:
- path: NBi.Core.SqlServer\bin\
  name: NBi.SqlServer
- path: .nupkg\NBi.SqlServer.*.nupkg
  name: NBi.SqlServer
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true
- description: ''
  provider: GitHub
  auth_token:
    secure: Gr2fraoXD6EyzbJJTfK+lk65/SO5SUaeQNzN51G2BB+wiS95xBeiFcl/8k5LP1h8
  artifact: NBi.SqlServer
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
