pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  BuildConfiguration: Debug
  BuildPlatform: Any CPU
  Parameters.solution: NBi.SqlServer.sln

steps:
- script: 'gitversion /l console /output buildserver /updateAssemblyInfo'
  displayName: 'Run GitVersion'
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: VSBuild@1
  displayName: 'Build $(Parameters.solution)'
  inputs:
    solution: '$(Parameters.solution)'
    vsVersion: 15.0
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: 'NBi.Testing*\\bin\\debug\\NBi.Testing*.dll'
    testFiltercriteria: 'TestCategory!=Olap & TestCategory!=Etl & TestCategory!=WindowsService & TestCategory!=ReportServerDB & TestCategory!=LocalSQL'
    vsTestVersion: 15.0
    codeCoverageEnabled: false
    diagnosticsEnabled: True

- task: PowerShell@2
  displayName: 'Package Nuget'
  inputs:
    targetType: filePath
    filePath: './.packages\\package-NBi-SqlServer.ps1'
    arguments: '$env:GitVersion_NuGetVersionV2'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\\Addin'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\\NBi.Core.SqlServer\\bin\\Debug\\'
    TargetFolder: '$(build.artifactstagingdirectory)\\Addin'
    CleanTargetFolder: true
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\Packages'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\.nupkg'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)\Packages'
    CleanTargetFolder: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;'
    publishVstsFeed: '0b85ebc7-d3b9-4844-886e-848213247f91'
    allowPackageConflicts: true
